### ISSUE TITLE
Exception-org.apache.commons.math.stat.descriptive.moment.Variance.evaluate.245

### ISSUE THREAD

**Issue by lylytran** [llmhyy/evosuite_progress#16]
Hi Lin Yun, 
this is the testcase: 
org.apache.commons.math.stat.descriptive.moment.Variance.evaluate() line 245
I think this could come frome the same issue, but the behaviors are different between the executions, you might find one of these two exceptions:
1. The assertion is in BranchCoverageSuiteFitness.getFitness() line 483
2. MonotonicGA.generateSolution() line 264: goal.getBranch() is null

**Comment by llmhyy** [comment]
it is a trivial case, where the methods in library is not the same as what we check in source code.
