### ISSUE TITLE
Filter Methods that Evosuite Cannot Evolve

### ISSUE THREAD

**Issue by llmhyy** [llmhyy/evosuite_progress#19]
Hi Lyly @lylytran 

I just checked the method org.apache.commons.math.dfp.Dfp.sqrt.1859. The reason for branch and fbranch to be equal is because it took Evosuite over 200s to run 50 test cases. In other word, the initialization of the Dfp object is very time consuming. 

In this regard, we should not consider such methods for experiment. There is an output information called `age`, which records the number of generations evolved by Evosuite. We can use branch fitness to run a method, if it returns 0 generations, it is either a trivial method (with branches very easy to cover, or has evolving problem), we can ignore them.

Many thanks!

**Comment by llmhyy** [comment]
Hi lyly @lylytran 

Do you have problem on this issue? Thanks!

**Comment by lylytran** [comment]
I'm still running the remained methods. I'll apply that filter to get the
final list of methods after having the complete report.
