### ISSUE TITLE
Interprocedural Method Profile

### ISSUE THREAD

**Issue by llmhyy** [llmhyy/evosuite_progress#34]
Hi lyly

For each called flag method of a method suffering from interprocedural flag problem (7k flag method), investigate four dimensions (features) for a method, please check the following template.

[template.xlsx](https://github.com/llmhyy/evosuite_progress/files/2865757/template.xlsx)

**Comment by lylytran** [comment]
the report is generated as  evosuite/EvosuiteTest/experiments/SF100/reports/flagMethodProfiles.xlsx
