### ISSUE TITLE
Batch Experiment for Evosuite

### ISSUE THREAD

**Issue by llmhyy** [llmhyy/evosuite_progress#9]
Hi @lylytran 

1. Write a check-function to filter methods with no branches.
2. Collect number of methods we need to run to decide how long we need to run for a method.
3. Run batch with evosuite in two modes (evosuite and random).

For the 3rd point, Guanjie may help to ask Zhang Fan's machine to this end.

**Comment by lylytran** [comment]
committed at rev. 0e44f779439f5c929f03ac0c461725580c724730 [0e44f77
